# Tutorials

There are various tutorials to run through for different sections of this website.
Below shows you the order and how to run each tutorial.

Important notes about these tutorials:

- Progress is saved: If you close the tutorial and reopen it on the same computer & RStudio it will continue from where you left off.
- Run in browser: You can click on the "Open in Browser" button at the top of the RStudio window with the tutorial to open the tutorial in a web browser.
- Split screen: The intended way to run through the tutorials is with the tutorial on one half of your screen and this website at the relvant page on the other half.

## Tibble

The first tutorial is on __Tibbles__.

To run the tutorial run the below [`learnr`](https://rstudio.github.io/learnr/) command.

__Note:__ Ensure you have followed the [install directions before this](learnr.qmd).

```{r, eval=FALSE}
learnr::run_tutorial("tibbles", package = "neoftidytutorials")
```

Whilst running through the tutorial refer to the [Tibble section of this website](/tibble/tibble.qmd).
