---
title: "Lterdatasampler"
format: html
---

__Lterdatasampler__ is a R package containing various datasets.
These datasets were generated by the [Long Term Ecological Research program (LTER) Network](https://lternet.edu/).
They were curated into a R package by [Allison Horst](https://allisonhorst.com/) and [Julien Brun](https://brunj7.github.io/).

For full information please see the [lterdatasampler website](https://lter.github.io/lterdatasampler/)

## Install and load

Installation and loading instruction below:

```{r, eval=FALSE}
install.packages("lterdatasampler")
library("lterdatasampler")
```

## Summary of datasets

List of the datasets within the package (as of 25th April 2025)

- [and_vertebrates](https://lter.github.io/lterdatasampler/reference/and_vertebrates.html): Records for aquatic vertebrates (cutthroat trout and salamanders) in Mack Creek, Andrews Experimental Forest, Oregon (1987 - present)
- [arc_weather](https://lter.github.io/lterdatasampler/reference/arc_weather.html): Daily meteorological (e.g. air temperature, precipitation) records from Toolik Field Station, Alaska (1988 - present)
- [hbr_maples](https://lter.github.io/lterdatasampler/reference/hbr_maples.html): Sugar maple seedlings at Hubbard Brook Experimental Forest (New Hampshire) in calcium-treated and reference watersheds in August 2003 and June 2004
- [knz_bison](https://lter.github.io/lterdatasampler/reference/knz_bison.html): Bison masses recorded for the herd at Konza Prairie Biological Station LTER
- [luq_streamchem](https://lter.github.io/lterdatasampler/reference/luq_streamchem.html): stream chemistry data for the Quebrada Sonadora (QS) location part of the Luqillo tropical forest LTER site
- [ntl_icecover](https://lter.github.io/lterdatasampler/reference/ntl_icecover.html): Ice freeze and thaw dates for Madison, Wisconsin Area lakes (1853 - 2019), North Temperate Lakes LTER
- [ntl_airtemp](https://lter.github.io/lterdatasampler/reference/ntl_airtemp.html): Daily average air temperature data for Madison, Wisconsin (1869 - 2019), North Temperate Lakes LTER
- [nwt_pikas](https://lter.github.io/lterdatasampler/reference/nwt_pikas.html): Pika observations for habitat and stress analysis at Niwot Ridge LTER, Colorado
- [pie_crab](https://lter.github.io/lterdatasampler/reference/pie_crab.html): Fiddler crab body size recorded summer 2016 in salt marshes from Florida to Massachusetts including Plum Island Ecosystem LTER, Virginia Coast LTER, and NOAA’s National Estuarine Research Reserve System


